# Generated by Django 3.1 on 2021-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
