# Generated by Django 3.1 on 2020-11-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20201128_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
