# Generated by Django 3.1 on 2021-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('imagePoster', models.URLField(blank=True, null=True)),
                ('imagePage', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('occurence', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='Weekly', max_length=250)),
                ('eventDate', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
