# Generated by Django 3.1 on 2021-01-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='occurence',
            field=models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly'), ('D', 'Daily'), ('W', 'Weekly')], default='Weekly', max_length=250),
        ),
    ]
