# Generated by Django 3.1 on 2021-01-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210116_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='occurence',
            field=models.CharField(choices=[('W', 'Weekly'), ('Y', 'Yearly'), ('M', 'Monthly'), ('D', 'Daily')], default='Weekly', max_length=250),
        ),
    ]
