# Generated by Django 3.1 on 2021-01-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210116_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='occurence',
            field=models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly'), ('W', 'Weekly'), ('D', 'Daily')], default='Weekly', max_length=250),
        ),
    ]
