# Generated by Django 3.1 on 2021-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210117_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='occurence',
            field=models.CharField(choices=[('Y', 'Yearly'), ('M', 'Monthly'), ('D', 'Daily'), ('W', 'Weekly')], default='Weekly', max_length=250),
        ),
    ]
