# Generated by Django 3.1 on 2021-01-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210117_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='occurence',
            field=models.CharField(choices=[('W', 'Weekly'), ('D', 'Daily'), ('M', 'Monthly'), ('Y', 'Yearly')], default='Weekly', max_length=250),
        ),
    ]
