# Generated by Django 3.1 on 2021-01-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210116_2135'),
        ('event', '0009_auto_20210118_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='occurence',
            field=models.CharField(choices=[('Y', 'Yearly'), ('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily')], default='Weekly', max_length=250),
        ),
        migrations.CreateModel(
            name='Event_Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
    ]
