# Generated by Django 3.1 on 2021-01-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20210118_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='occurence',
            field=models.CharField(choices=[('W', 'Weekly'), ('Y', 'Yearly'), ('D', 'Daily'), ('M', 'Monthly'), ('O', 'Once')], default='Weekly', max_length=250),
        ),
    ]
