# Generated by Django 3.1 on 2021-01-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20210122_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='occurence',
            field=models.CharField(choices=[('Y', 'Yearly'), ('O', 'Once'), ('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily')], default='Weekly', max_length=250),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worshipLeader', models.CharField(max_length=500, null=True)),
                ('scripture', models.CharField(max_length=500, null=True)),
                ('reader', models.CharField(max_length=500, null=True)),
                ('preacher', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
