# Generated by Django 3.1 on 2021-01-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0002_auto_20210116_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='item',
        ),
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
