# Generated by Django 3.1 on 2021-01-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0003_auto_20210117_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
